### ISSUE TITLE
发送请求方法问题

### ISSUE THREAD

**Issue by lgyhitler** [node-weixin/node-weixin-pay#1]
发现支付这块请求接口比较特殊的几点：
1、需要证书加密的xmlssl请求（涉及退款功能的接口）
2、无需证书加密的xml（大部分接口）
3、微信接口直接返回文本表格（订单对账接口）
目前pay模块发送请求request方法中用的都是 xmlssl方法，对上述有两种方式并不支持。
感觉需要完善一下~

**Comment by calidion** [comment]
@lgyhitler 
目前支付的请求应该都是基于HTTPS的。
所以pay里使用HTTPS应该是正确的。
不知道你说的是什么问题？

**Comment by lgyhitler** [comment]
问题一、微信支付有些接口需要传递商户的支付接口证书文件，但是有些接口不用传，但是代码里统一都调用的xmlssl方法，这个方法要求必须传证书文件的，感觉欠妥。
问题二、微信支付对账接口正常业务返回的并不是xml格式的内容，而是一个大文本。xml2json时候会报错。目前仅发现这一个接口是这样

发自我的 iPhone

在 2016年8月9日，18:24，Eric <notifications@github.com<mailto:notifications@github.com>> 写道：


@lgyhitler<https://github.com/lgyhitler>
目前支付的请求应该都是基于HTTPS的。
所以pay里使用HTTPS应该是正确的。
不知道你说的是什么问题？

―

**Comment by calidion** [comment]
@lgyhitler 
1. 理解了。
2. 估计是脱掉壳后不是XML。
方便可以发个PR。

**Comment by lgyhitler** [comment]
ok.最近在升级node版本，寻思把依赖也都升级一下，然后就给自己挖坑了…o(s□t)o

发自我的 iPhone

在 2016年8月9日，18:48，Eric <notifications@github.com<mailto:notifications@github.com>> 写道：


@lgyhitler<https://github.com/lgyhitler>
1. 理解了。
2. 估计是脱掉壳后不是XML。
方便可以发个PR。

―

**Comment by calidion** [comment]
升级不是好事。
我已经将greenkeeper之类的全部都禁用了。
稳定压到一切，除非软件有缺陷。

**Comment by lgyhitler** [comment]
这个很同意，不过介于我们版本略低0.10.35，还是稳定到stl版吧。

发自我的 iPhone

在 2016年8月10日，00:44，Eric <notifications@github.com<mailto:notifications@github.com>> 写道：


升级不是好事。
我已经将greenkeeper之类的全部都禁用了。
稳定压到一切，除非软件有缺陷。

―
